server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启注册中心路由功能
      #          lower-case-service-id: true
      routes:
        - id: payment_routh
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service #此处如果有问题，请注意依赖spring-cloud-starter-netflix-eureka-client依赖不能错
          predicates:
            - Path=/payment/get/**

#        - id: my_route
#          uri: lb://my-load-balanced-service
#          predicates:
#            - Path=/payment/lb/**

        - id: payment_routh2
          #          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#my-load-balanced-service:
#  ribbon:
#    listOfServers: http://localhost:8001, http://localhost:8002
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka
#logging:
#  level:
#    root: debug

