server:
  port: 80


eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
  instance:
    instance-id: order80
    prefer-ip-address: true   #访问路径可以显示IP地址
#设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  application:
    name: cloud-order-feign-80
logging:
  level:
    com.kyw.springcloud.service.PaymentFeignService: debug